"""empty message

Revision ID: 4296d3041f33
Revises: eaa74adff781
Create Date: 2024-03-11 09:29:26.627560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4296d3041f33'
down_revision = 'eaa74adff781'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Customers', schema=None) as batch_op:
        batch_op.drop_column('budget')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
