"""empty message

Revision ID: 576c2c05db80
Revises: 3f08927c0b3d
Create Date: 2024-03-11 21:59:02.545194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '576c2c05db80'
down_revision = '3f08927c0b3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Agents', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=30),
               nullable=True)
        batch_op.create_unique_constraint(None, ['phone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Agents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('phone',
               existing_type=sa.String(length=30),
               type_=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
