"""empty message

Revision ID: 6bd11e29b088
Revises: 4296d3041f33
Create Date: 2024-03-11 11:02:38.015320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bd11e29b088'
down_revision = '4296d3041f33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Realty', schema=None) as batch_op:
        batch_op.add_column(sa.Column('square', sa.String(length=10), nullable=False))
        batch_op.drop_column('area')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Realty', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('square')

    # ### end Alembic commands ###
