"""empty message

Revision ID: 977ec4ba85ec
Revises: 3423da06a73f
Create Date: 2024-03-11 11:08:32.700677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '977ec4ba85ec'
down_revision = '3423da06a73f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Realty', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Realty', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)

    # ### end Alembic commands ###
